# Generated by Django 3.2.13 on 2022-05-13 06:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(1)])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('race', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('size', models.CharField(choices=[('small', 'small'), ('average', 'average'), ('big', 'big')], max_length=7)),
                ('hobby', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('med', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
