# Generated by Django 4.0.3 on 2022-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounts_date_of_birth_alter_accounts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='approved',
            field=models.BooleanField(blank=True),
        ),
    ]
