# Generated by Django 4.0.3 on 2022-04-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_is_check_accounts_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='is_checked',
        ),
    ]
