# Generated by Django 4.0.3 on 2022-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accounts_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('title', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_admin',
        ),
    ]
