pipeline {
        agent {
            docker { image 'python:3.8' }
        }
         stages {
            stage('Build') {
                steps {
                        
                         
                        withEnv(["HOME=${env.WORKSPACE}"]){
                                sh 'python3 -m pip install --upgrade pip setuptools wheel'
                                sh 'pip install pipenv'
                        } 
                }
                
            }
            stage('Test') {
//                     agent {
//                             docker {
//                                     image 'qnib/pytest'
//                             }
//                     }
                steps {
                        withEnv(["HOME=${env.WORKSPACE}"]){
                             
                                //sh 'py.test --verbose --junit-xml-reports/results.xml accounts/tests.py'
                                sh 'python accounts/manage.py test'
                        }
                }
//                     post {always {'reports/results.xml'
//                                  }
//                          }
            }
        }
       
    }
