pipeline {
        agent {
            docker { image 'python:3.8' }
        }
         stages {
            stage('Build') {
                steps {
                        
                         
                        withEnv(["HOME=${env.WORKSPACE}"]){
                                sh 'python3 -m pip install --upgrade pip setuptools wheel'
                                sh 'pip install pipenv'
                        } 
                }
                
            }
            stage('Test') {
                steps {
                        withEnv(["HOME=${env.WORKSPACE}"]){
                  
                                sh 'python manage.py test'
                        }
                }
            }
        }
       
    }
