# Generated by Django 4.0.3 on 2022-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_address_accounts_is_doggiesitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
    ]
