# Generated by Django 4.0.3 on 2022-04-10 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.CharField(default=18, max_length=3, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(default='10 digits long phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.CharField(default="City, Neighborhood, Street, Apt. No., etc'", max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default='9 digits long id number', max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
