# Generated by Django 4.0.3 on 2022-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_accounts_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
