# Generated by Django 4.0.3 on 2022-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_postterms_remove_accounts_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
