# Generated by Django 4.0.3 on 2022-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accounts_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='address',
        ),
        migrations.AddField(
            model_name='accounts',
            name='Aprt',
            field=models.CharField(default='Aprt. number', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='neighborhood',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='street',
            field=models.CharField(default='street and number', max_length=50),
        ),
    ]
