# Generated by Django 4.0.3 on 2022-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
