# Generated by Django 4.0.3 on 2022-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('about', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
