# Generated by Django 4.0.3 on 2022-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_postfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeedback',
            name='type',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
