# Generated by Django 4.0.3 on 2022-05-19 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_postfeedback_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_owner', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('address', models.TextField()),
                ('comments', models.TextField()),
                ('doggiesitter', models.TextField()),
            ],
        ),
    ]
