# Generated by Django 4.0.3 on 2022-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeedback',
            name='author',
            field=models.TextField(max_length=50),
        ),
    ]
