# Generated by Django 4.0.3 on 2022-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_aprt_accounts_aprt_alter_trip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='endtime',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
