# Generated by Django 4.0.3 on 2022-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_trip_id_trip_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
